--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 10100).Seccion:CERAMICA
UPDATE PRODUCTOS
SET Precio = 10100
WHERE CodArticulo = '11' AND Seccion = 'CERAMICA'
GO
UPDATE PRODUCTOS
SET Precio = 10101
WHERE CodArticulo = '15' AND Seccion = 'CERAMICA'
GO
UPDATE PRODUCTOS
SET Precio = 10102
WHERE CodArticulo = '20' AND Seccion = 'CERAMICA'
GO
UPDATE PRODUCTOS
SET Precio = 10103
WHERE CodArticulo = '21' AND Seccion = 'CERAMICA'
GO
UPDATE PRODUCTOS
SET Precio = 10104
WHERE CodArticulo = '33' AND Seccion = 'CERAMICA'
GO
UPDATE PRODUCTOS
SET Precio = 10105
WHERE CodArticulo = '39' AND Seccion = 'CERAMICA'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 20100).Seccion:CONFECCION
UPDATE PRODUCTOS
SET Precio = 20100
WHERE CodArticulo = '2' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20101
WHERE CodArticulo = '7' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20102
WHERE CodArticulo = '9' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20103
WHERE CodArticulo = '13' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20104
WHERE CodArticulo = '19' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20105
WHERE CodArticulo = '23' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20106
WHERE CodArticulo = '27' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20107
WHERE CodArticulo = '29' AND Seccion = 'CONFECCION'
GO
UPDATE PRODUCTOS
SET Precio = 20108
WHERE CodArticulo = '37' AND Seccion = 'CONFECCION'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 30100).Seccion:DEPORTES
UPDATE PRODUCTOS
SET Precio = 30100
WHERE CodArticulo = '4' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30101
WHERE CodArticulo = '6' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30102
WHERE CodArticulo = '18' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30103
WHERE CodArticulo = '24' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30104
WHERE CodArticulo = '25' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30105
WHERE CodArticulo = '28' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30106
WHERE CodArticulo = '32' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30107
WHERE CodArticulo = '38' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30108
WHERE CodArticulo = '40' AND Seccion = 'DEPORTES'
GO
UPDATE PRODUCTOS
SET Precio = 30109
WHERE CodArticulo = '41' AND Seccion = 'DEPORTES'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 40100).Seccion:FERRETERIA
UPDATE PRODUCTOS
SET Precio = 40100
WHERE CodArticulo = '1' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40101
WHERE CodArticulo = '12' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40102
WHERE CodArticulo = '16' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40103
WHERE CodArticulo = '22' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40104
WHERE CodArticulo = '30' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40105
WHERE CodArticulo = '35' AND Seccion = 'FERRETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 40106
WHERE CodArticulo = '36' AND Seccion = 'FERRETERIA'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 50100).Seccion:JUGUETERIA
UPDATE PRODUCTOS
SET Precio = 50100
WHERE CodArticulo = '3' AND Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50101
WHERE CodArticulo = '8' AND Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50102
WHERE CodArticulo = '10' AND Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50103
WHERE CodArticulo = '14' AND Seccion = 'JUGUETERIA'
GO
SELECT * FROM PRODUCTOS P WHERE P.Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50104
WHERE CodArticulo = '17' AND Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50105
WHERE CodArticulo = '26' AND Seccion = 'JUGUETERIA'
GO
UPDATE PRODUCTOS
SET Precio = 50106
WHERE CodArticulo = '31' AND Seccion = 'JUGUETERIA'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 60100).Seccion:OFICINA
UPDATE PRODUCTOS
SET Precio = 60100
WHERE CodArticulo = '34' AND Seccion = 'OFICINA'
GO




--Incrementar el precio de TODOS los SKU con un contador de 1 para cada unidad (SKU1 Inicia en 70100).Seccion:ALTA COSTURA
UPDATE PRODUCTOSNro2
SET Precio = 70100
WHERE CodArticulo = '50' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70101
WHERE CodArticulo = '53' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70102
WHERE CodArticulo = '54' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70103
WHERE CodArticulo = '55' AND Seccion = 'ALTA COSTURA' 
GO
UPDATE PRODUCTOSNro2
SET Precio = 70104
WHERE CodArticulo = '57' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70105
WHERE CodArticulo = '58' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70106
WHERE CodArticulo = '61' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70107
WHERE CodArticulo = '63' AND Seccion = 'ALTA COSTURA'
GO
UPDATE PRODUCTOSNro2
SET Precio = 70108
WHERE CodArticulo = '65' AND Seccion = 'ALTA COSTURA'
GO